USE [master]
GO

/****** Object:  Database [SuperShop]    Script Date: 17/10/2014 02:55:12 ******/
CREATE DATABASE [SuperShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SuperShop', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SuperShop.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SuperShop_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SuperShop_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SuperShop] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SuperShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SuperShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SuperShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SuperShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SuperShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SuperShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [SuperShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SuperShop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SuperShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SuperShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SuperShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SuperShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SuperShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SuperShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SuperShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SuperShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SuperShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SuperShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SuperShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SuperShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SuperShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SuperShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SuperShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SuperShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SuperShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SuperShop] SET  MULTI_USER 
GO

ALTER DATABASE [SuperShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SuperShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SuperShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SuperShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SuperShop] SET  READ_WRITE 
GO

